<div class="container">
    <div class="row">
        <button type="button" class="btn btn-sm emojis">😁</button>
        <button type="button" class="btn btn-sm emojis">😂</button>
        <button type="button" class="btn btn-sm emojis">😃</button>
        <button type="button" class="btn btn-sm emojis">😄</button>
        <button type="button" class="btn btn-sm emojis">😅</button>
        <button type="button" class="btn btn-sm emojis">😆</button>
        <button type="button" class="btn btn-sm emojis">😉</button>
        <button type="button" class="btn btn-sm emojis">😊</button>
        <button type="button" class="btn btn-sm emojis">😋</button>
        <button type="button" class="btn btn-sm emojis">😌</button>
        <button type="button" class="btn btn-sm emojis">😍</button>
        <button type="button" class="btn btn-sm emojis">😏</button>
        <button type="button" class="btn btn-sm emojis">😒</button>
        <button type="button" class="btn btn-sm emojis">😓</button>
        <button type="button" class="btn btn-sm emojis">😔</button>
        <button type="button" class="btn btn-sm emojis">😖</button>
        <button type="button" class="btn btn-sm emojis">😘</button>
        <button type="button" class="btn btn-sm emojis">😚</button>
        <button type="button" class="btn btn-sm emojis">😜</button>
        <button type="button" class="btn btn-sm emojis">😝</button>
        <button type="button" class="btn btn-sm emojis">😞</button>
        <button type="button" class="btn btn-sm emojis">😠</button>
        <button type="button" class="btn btn-sm emojis">😢</button>
        <button type="button" class="btn btn-sm emojis">😤</button>
        <button type="button" class="btn btn-sm emojis">😥</button>
        <button type="button" class="btn btn-sm emojis">😨</button>
        <button type="button" class="btn btn-sm emojis">😩</button>
        <button type="button" class="btn btn-sm emojis">😪</button>
        <button type="button" class="btn btn-sm emojis">😫</button>
        <button type="button" class="btn btn-sm emojis">😭</button>
        <button type="button" class="btn btn-sm emojis">😰</button>
        <button type="button" class="btn btn-sm emojis">😱</button>
        <button type="button" class="btn btn-sm emojis">😲</button>
        <button type="button" class="btn btn-sm emojis">😳</button>
        <button type="button" class="btn btn-sm emojis">😵</button>
        <button type="button" class="btn btn-sm emojis">😷</button>
        <button type="button" class="btn btn-sm emojis">😸</button>
        <button type="button" class="btn btn-sm emojis">😹</button>
        <button type="button" class="btn btn-sm emojis">😺</button>
        <button type="button" class="btn btn-sm emojis">😻</button>
        <button type="button" class="btn btn-sm emojis">😼</button>
        <button type="button" class="btn btn-sm emojis">😽</button>
        <button type="button" class="btn btn-sm emojis">😾</button>
        <button type="button" class="btn btn-sm emojis">😿</button>
        <button type="button" class="btn btn-sm emojis">🙀</button>
        <button type="button" class="btn btn-sm emojis">🙅</button>
        <button type="button" class="btn btn-sm emojis">🙆</button>
        <button type="button" class="btn btn-sm emojis">🙇</button>
        <button type="button" class="btn btn-sm emojis">👀</button>
        <button type="button" class="btn btn-sm emojis">💖</button>
        <button type="button" class="btn btn-sm emojis">💕</button>
        <button type="button" class="btn btn-sm emojis">💗</button>
        <button type="button" class="btn btn-sm emojis">💝</button>
        <button type="button" class="btn btn-sm emojis">💋</button>
        <button type="button" class="btn btn-sm emojis">💐</button>
        <button type="button" class="btn btn-sm emojis">💩</button>
        <button type="button" class="btn btn-sm emojis">🙋</button>
        <button type="button" class="btn btn-sm emojis">🙌</button>
        <button type="button" class="btn btn-sm emojis">🙍</button>
        <button type="button" class="btn btn-sm emojis">🙎</button>
        <button type="button" class="btn btn-sm emojis">🙏</button>
    </div>
</div>
