<div class="container scroll-emojis">
    <div class="row p-3">
        <button type="button" class="btn btn-sm emojis">😁</button>
        <button type="button" class="btn btn-sm emojis">😂</button>
        <button type="button" class="btn btn-sm emojis">🤣</button>
        <button type="button" class="btn btn-sm emojis">😃</button>
        <button type="button" class="btn btn-sm emojis">😄</button>
        <button type="button" class="btn btn-sm emojis">😅</button>
        <button type="button" class="btn btn-sm emojis">😆</button>
        <button type="button" class="btn btn-sm emojis">😉</button>
        <button type="button" class="btn btn-sm emojis">😊</button>
        <button type="button" class="btn btn-sm emojis">😋</button>
        <button type="button" class="btn btn-sm emojis">😌</button>
        <button type="button" class="btn btn-sm emojis">😍</button>
        <button type="button" class="btn btn-sm emojis">😏</button>
        <button type="button" class="btn btn-sm emojis">😒</button>
        <button type="button" class="btn btn-sm emojis">😓</button>
        <button type="button" class="btn btn-sm emojis">🥰</button>
        <button type="button" class="btn btn-sm emojis">😇</button>
        <button type="button" class="btn btn-sm emojis">😘</button>
        <button type="button" class="btn btn-sm emojis">😚</button>
        <button type="button" class="btn btn-sm emojis">😜</button>
        <button type="button" class="btn btn-sm emojis">😝</button>
        <button type="button" class="btn btn-sm emojis">😎</button>
        <button type="button" class="btn btn-sm emojis">😠</button>
        <button type="button" class="btn btn-sm emojis">😢</button>
        <button type="button" class="btn btn-sm emojis">😤</button>
        <button type="button" class="btn btn-sm emojis">😥</button>
        <button type="button" class="btn btn-sm emojis">😨</button>
        <button type="button" class="btn btn-sm emojis">😩</button>
        <button type="button" class="btn btn-sm emojis">😪</button>
        <button type="button" class="btn btn-sm emojis">😫</button>
        <button type="button" class="btn btn-sm emojis">😭</button>
        <button type="button" class="btn btn-sm emojis">😰</button>
        <button type="button" class="btn btn-sm emojis">😱</button>
        <button type="button" class="btn btn-sm emojis">😲</button>
        <button type="button" class="btn btn-sm emojis">😳</button>
        <button type="button" class="btn btn-sm emojis">😮</button>
        <button type="button" class="btn btn-sm emojis">😷</button>
        <button type="button" class="btn btn-sm emojis">😸</button>
        <button type="button" class="btn btn-sm emojis">😹</button>
        <button type="button" class="btn btn-sm emojis">😺</button>
        <button type="button" class="btn btn-sm emojis">😻</button>
        <button type="button" class="btn btn-sm emojis">😼</button>
        <button type="button" class="btn btn-sm emojis">😽</button>
        <button type="button" class="btn btn-sm emojis">😾</button>
        <button type="button" class="btn btn-sm emojis">😿</button>
        <button type="button" class="btn btn-sm emojis">🙀</button>
        <button type="button" class="btn btn-sm emojis">🙅</button>
        <button type="button" class="btn btn-sm emojis">🙆</button>
        <button type="button" class="btn btn-sm emojis">🙇</button>
        <button type="button" class="btn btn-sm emojis">👀</button>
        <button type="button" class="btn btn-sm emojis">💖</button>
        <button type="button" class="btn btn-sm emojis">💕</button>
        <button type="button" class="btn btn-sm emojis">💗</button>
        <button type="button" class="btn btn-sm emojis">💝</button>
        <button type="button" class="btn btn-sm emojis">💋</button>
        <button type="button" class="btn btn-sm emojis">💐</button>
        <button type="button" class="btn btn-sm emojis">💩</button>
        <button type="button" class="btn btn-sm emojis">🤥</button>
        <button type="button" class="btn btn-sm emojis">👋</button>
        <button type="button" class="btn btn-sm emojis">🤚</button>
        <button type="button" class="btn btn-sm emojis">🖐</button>
        <button type="button" class="btn btn-sm emojis">✋</button>
        <button type="button" class="btn btn-sm emojis">🖖</button>
        <button type="button" class="btn btn-sm emojis">👌</button>
        <button type="button" class="btn btn-sm emojis">🤏</button>
        <button type="button" class="btn btn-sm emojis">✌</button>
        <button type="button" class="btn btn-sm emojis">🤞</button>
        <button type="button" class="btn btn-sm emojis">🤟</button>
        <button type="button" class="btn btn-sm emojis">🤘</button>
        <button type="button" class="btn btn-sm emojis">🤙</button>
        <button type="button" class="btn btn-sm emojis">👈</button>
        <button type="button" class="btn btn-sm emojis">👉</button>
        <button type="button" class="btn btn-sm emojis">👆</button>
        <button type="button" class="btn btn-sm emojis">🖕</button>
        <button type="button" class="btn btn-sm emojis">👇</button>
        <button type="button" class="btn btn-sm emojis">☝</button>
        <button type="button" class="btn btn-sm emojis">👍</button>
        <button type="button" class="btn btn-sm emojis">👎</button>
        <button type="button" class="btn btn-sm emojis">✊</button>
        <button type="button" class="btn btn-sm emojis">👊</button>
        <button type="button" class="btn btn-sm emojis">🤛</button>
        <button type="button" class="btn btn-sm emojis">🤜</button>
        <button type="button" class="btn btn-sm emojis">👏</button>
        <button type="button" class="btn btn-sm emojis">🙌</button>
        <button type="button" class="btn btn-sm emojis">👐</button>
        <button type="button" class="btn btn-sm emojis">🤲</button>
        <button type="button" class="btn btn-sm emojis">🤝</button>
        <button type="button" class="btn btn-sm emojis">🙏</button>
        <button type="button" class="btn btn-sm emojis">💪</button>
    </div>
</div>
